apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 2 # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: 819254154653.dkr.ecr.us-east-2.amazonaws.com/hotstarimage:latest
        ports:
        - containerPort: 3000  # Port your application listens on
